# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'J:\Projects\GoDaddyDNSApp\GoDaddyDNSApp\ui\dnsquickedit.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DNSQuickEdit(object):
    def setupUi(self, DNSQuickEdit):
        DNSQuickEdit.setObjectName("DNSQuickEdit")
        DNSQuickEdit.resize(360, 173)
        DNSQuickEdit.setMaximumSize(QtCore.QSize(360, 173))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DNSQuickEdit.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(DNSQuickEdit)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.domainDropDown = QtWidgets.QComboBox(self.centralwidget)
        self.domainDropDown.setObjectName("domainDropDown")
        self.domainDropDown.addItem("")
        self.domainDropDown.addItem("")
        self.domainDropDown.addItem("")
        self.domainDropDown.addItem("")
        self.domainDropDown.addItem("")
        self.verticalLayout_2.addWidget(self.domainDropDown)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.recordTypeDropDown = QtWidgets.QComboBox(self.centralwidget)
        self.recordTypeDropDown.setObjectName("recordTypeDropDown")
        self.recordTypeDropDown.addItem("")
        self.recordTypeDropDown.addItem("")
        self.recordTypeDropDown.addItem("")
        self.horizontalLayout.addWidget(self.recordTypeDropDown)
        self.ttlDropDown = QtWidgets.QComboBox(self.centralwidget)
        self.ttlDropDown.setObjectName("ttlDropDown")
        self.ttlDropDown.addItem("")
        self.ttlDropDown.addItem("")
        self.ttlDropDown.addItem("")
        self.horizontalLayout.addWidget(self.ttlDropDown)
        self.priorityDropDown = QtWidgets.QComboBox(self.centralwidget)
        self.priorityDropDown.setEnabled(False)
        self.priorityDropDown.setObjectName("priorityDropDown")
        self.priorityDropDown.addItem("")
        self.priorityDropDown.addItem("")
        self.priorityDropDown.addItem("")
        self.priorityDropDown.addItem("")
        self.priorityDropDown.addItem("")
        self.horizontalLayout.addWidget(self.priorityDropDown)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.hostEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.hostEdit.setObjectName("hostEdit")
        self.verticalLayout.addWidget(self.hostEdit)
        self.pointsToEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pointsToEdit.setObjectName("pointsToEdit")
        self.verticalLayout.addWidget(self.pointsToEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.addRecordButton = QtWidgets.QPushButton(self.centralwidget)
        self.addRecordButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.addRecordButton.setObjectName("addRecordButton")
        self.horizontalLayout_2.addWidget(self.addRecordButton)
        self.updateRecordButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateRecordButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.updateRecordButton.setObjectName("updateRecordButton")
        self.horizontalLayout_2.addWidget(self.updateRecordButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        DNSQuickEdit.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(DNSQuickEdit)
        self.statusBar.setObjectName("statusBar")
        DNSQuickEdit.setStatusBar(self.statusBar)

        self.retranslateUi(DNSQuickEdit)
        QtCore.QMetaObject.connectSlotsByName(DNSQuickEdit)

    def retranslateUi(self, DNSQuickEdit):
        _translate = QtCore.QCoreApplication.translate
        DNSQuickEdit.setWindowTitle(_translate("DNSQuickEdit", "QuickDNSUpdate"))
        self.domainDropDown.setItemText(0, _translate("DNSQuickEdit", "lnxsystems.com"))
        self.domainDropDown.setItemText(1, _translate("DNSQuickEdit", "jnvilo.com"))
        self.domainDropDown.setItemText(2, _translate("DNSQuickEdit", "maltacentral.com"))
        self.domainDropDown.setItemText(3, _translate("DNSQuickEdit", "igamingdb.com"))
        self.domainDropDown.setItemText(4, _translate("DNSQuickEdit", "lnxworld.com"))
        self.recordTypeDropDown.setItemText(0, _translate("DNSQuickEdit", "A"))
        self.recordTypeDropDown.setItemText(1, _translate("DNSQuickEdit", "CNAME"))
        self.recordTypeDropDown.setItemText(2, _translate("DNSQuickEdit", "MX"))
        self.ttlDropDown.setToolTip(_translate("DNSQuickEdit", "TTL "))
        self.ttlDropDown.setItemText(0, _translate("DNSQuickEdit", "600"))
        self.ttlDropDown.setItemText(1, _translate("DNSQuickEdit", "1800"))
        self.ttlDropDown.setItemText(2, _translate("DNSQuickEdit", "3600"))
        self.priorityDropDown.setToolTip(_translate("DNSQuickEdit", "Priority "))
        self.priorityDropDown.setItemText(0, _translate("DNSQuickEdit", "10"))
        self.priorityDropDown.setItemText(1, _translate("DNSQuickEdit", "20"))
        self.priorityDropDown.setItemText(2, _translate("DNSQuickEdit", "30"))
        self.priorityDropDown.setItemText(3, _translate("DNSQuickEdit", "40"))
        self.priorityDropDown.setItemText(4, _translate("DNSQuickEdit", "50"))
        self.hostEdit.setToolTip(_translate("DNSQuickEdit", "hostname "))
        self.addRecordButton.setText(_translate("DNSQuickEdit", "Add Record"))
        self.updateRecordButton.setText(_translate("DNSQuickEdit", "Add or Update Record"))

